# Generated by Django 3.2.11 on 2022-01-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0002_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='room_id',
            new_name='room',
        ),
    ]
